CREATE DATABASE CADASTRO_FUNCIONARIOS;

USE CADASTRO_FUNCIONARIOS;


CREATE TABLE EMPREGADOR(
  COD_EMPRESA INT PRIMARY KEY NOT NULL,
  NOME_DA_EMPRESA VARCHAR(50),
  CNPJ VARCHAR(50)
);


CREATE TABLE EMPREGADO(
  COD_EMPREGADO INT PRIMARY KEY NOT NULL,
  NOME_DO_FUNCIONARIO VARCHAR(50),
  CPF_FUNCIONARIO VARCHAR(14) NOT NULL UNIQUE
);
