CREATE DATABASE CADASTRO_FUNCIONARIOS
GO
USE CADASTRO_FUNCIONARIOS
GO

CREATE TABLE(
  COD_EMPRESA INT PRIMARY KEY NOT NULL,
  NOME_DA_EMPRESA VARCHAR(50),
  CNPJ VARCHAR(50),

);
GO

CREATE TABLE(
  COD_EMPREGADO INT PRIMARY KEY IDENTITY(100,1),
  NOME_DO_FUNCIONARIO VARCHAR(50),
  CPF_FUNCIONARIO VARCHAR(14) NOT NULL UNIQUE,

);
